require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BoardshortmessagesController do

  # This should return the minimal set of attributes required to create a valid
  # Boardshortmessage. As you add validations to Boardshortmessage, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "board_id" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BoardshortmessagesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all boardshortmessages as @boardshortmessages" do
      boardshortmessage = Boardshortmessage.create! valid_attributes
      get :index, {}, valid_session
      assigns(:boardshortmessages).should eq([boardshortmessage])
    end
  end

  describe "GET show" do
    it "assigns the requested boardshortmessage as @boardshortmessage" do
      boardshortmessage = Boardshortmessage.create! valid_attributes
      get :show, {:id => boardshortmessage.to_param}, valid_session
      assigns(:boardshortmessage).should eq(boardshortmessage)
    end
  end

  describe "GET new" do
    it "assigns a new boardshortmessage as @boardshortmessage" do
      get :new, {}, valid_session
      assigns(:boardshortmessage).should be_a_new(Boardshortmessage)
    end
  end

  describe "GET edit" do
    it "assigns the requested boardshortmessage as @boardshortmessage" do
      boardshortmessage = Boardshortmessage.create! valid_attributes
      get :edit, {:id => boardshortmessage.to_param}, valid_session
      assigns(:boardshortmessage).should eq(boardshortmessage)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Boardshortmessage" do
        expect {
          post :create, {:boardshortmessage => valid_attributes}, valid_session
        }.to change(Boardshortmessage, :count).by(1)
      end

      it "assigns a newly created boardshortmessage as @boardshortmessage" do
        post :create, {:boardshortmessage => valid_attributes}, valid_session
        assigns(:boardshortmessage).should be_a(Boardshortmessage)
        assigns(:boardshortmessage).should be_persisted
      end

      it "redirects to the created boardshortmessage" do
        post :create, {:boardshortmessage => valid_attributes}, valid_session
        response.should redirect_to(Boardshortmessage.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved boardshortmessage as @boardshortmessage" do
        # Trigger the behavior that occurs when invalid params are submitted
        Boardshortmessage.any_instance.stub(:save).and_return(false)
        post :create, {:boardshortmessage => { "board_id" => "invalid value" }}, valid_session
        assigns(:boardshortmessage).should be_a_new(Boardshortmessage)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Boardshortmessage.any_instance.stub(:save).and_return(false)
        post :create, {:boardshortmessage => { "board_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested boardshortmessage" do
        boardshortmessage = Boardshortmessage.create! valid_attributes
        # Assuming there are no other boardshortmessages in the database, this
        # specifies that the Boardshortmessage created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Boardshortmessage.any_instance.should_receive(:update).with({ "board_id" => "MyString" })
        put :update, {:id => boardshortmessage.to_param, :boardshortmessage => { "board_id" => "MyString" }}, valid_session
      end

      it "assigns the requested boardshortmessage as @boardshortmessage" do
        boardshortmessage = Boardshortmessage.create! valid_attributes
        put :update, {:id => boardshortmessage.to_param, :boardshortmessage => valid_attributes}, valid_session
        assigns(:boardshortmessage).should eq(boardshortmessage)
      end

      it "redirects to the boardshortmessage" do
        boardshortmessage = Boardshortmessage.create! valid_attributes
        put :update, {:id => boardshortmessage.to_param, :boardshortmessage => valid_attributes}, valid_session
        response.should redirect_to(boardshortmessage)
      end
    end

    describe "with invalid params" do
      it "assigns the boardshortmessage as @boardshortmessage" do
        boardshortmessage = Boardshortmessage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Boardshortmessage.any_instance.stub(:save).and_return(false)
        put :update, {:id => boardshortmessage.to_param, :boardshortmessage => { "board_id" => "invalid value" }}, valid_session
        assigns(:boardshortmessage).should eq(boardshortmessage)
      end

      it "re-renders the 'edit' template" do
        boardshortmessage = Boardshortmessage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Boardshortmessage.any_instance.stub(:save).and_return(false)
        put :update, {:id => boardshortmessage.to_param, :boardshortmessage => { "board_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested boardshortmessage" do
      boardshortmessage = Boardshortmessage.create! valid_attributes
      expect {
        delete :destroy, {:id => boardshortmessage.to_param}, valid_session
      }.to change(Boardshortmessage, :count).by(-1)
    end

    it "redirects to the boardshortmessages list" do
      boardshortmessage = Boardshortmessage.create! valid_attributes
      delete :destroy, {:id => boardshortmessage.to_param}, valid_session
      response.should redirect_to(boardshortmessages_url)
    end
  end

end
