require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe WateringsController do

  # This should return the minimal set of attributes required to create a valid
  # Watering. As you add validations to Watering, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "time" => "2013-09-20 01:33:26" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # WateringsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all waterings as @waterings" do
      watering = Watering.create! valid_attributes
      get :index, {}, valid_session
      assigns(:waterings).should eq([watering])
    end
  end

  describe "GET show" do
    it "assigns the requested watering as @watering" do
      watering = Watering.create! valid_attributes
      get :show, {:id => watering.to_param}, valid_session
      assigns(:watering).should eq(watering)
    end
  end

  describe "GET new" do
    it "assigns a new watering as @watering" do
      get :new, {}, valid_session
      assigns(:watering).should be_a_new(Watering)
    end
  end

  describe "GET edit" do
    it "assigns the requested watering as @watering" do
      watering = Watering.create! valid_attributes
      get :edit, {:id => watering.to_param}, valid_session
      assigns(:watering).should eq(watering)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Watering" do
        expect {
          post :create, {:watering => valid_attributes}, valid_session
        }.to change(Watering, :count).by(1)
      end

      it "assigns a newly created watering as @watering" do
        post :create, {:watering => valid_attributes}, valid_session
        assigns(:watering).should be_a(Watering)
        assigns(:watering).should be_persisted
      end

      it "redirects to the created watering" do
        post :create, {:watering => valid_attributes}, valid_session
        response.should redirect_to(Watering.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved watering as @watering" do
        # Trigger the behavior that occurs when invalid params are submitted
        Watering.any_instance.stub(:save).and_return(false)
        post :create, {:watering => { "time" => "invalid value" }}, valid_session
        assigns(:watering).should be_a_new(Watering)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Watering.any_instance.stub(:save).and_return(false)
        post :create, {:watering => { "time" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested watering" do
        watering = Watering.create! valid_attributes
        # Assuming there are no other waterings in the database, this
        # specifies that the Watering created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Watering.any_instance.should_receive(:update).with({ "time" => "2013-09-20 01:33:26" })
        put :update, {:id => watering.to_param, :watering => { "time" => "2013-09-20 01:33:26" }}, valid_session
      end

      it "assigns the requested watering as @watering" do
        watering = Watering.create! valid_attributes
        put :update, {:id => watering.to_param, :watering => valid_attributes}, valid_session
        assigns(:watering).should eq(watering)
      end

      it "redirects to the watering" do
        watering = Watering.create! valid_attributes
        put :update, {:id => watering.to_param, :watering => valid_attributes}, valid_session
        response.should redirect_to(watering)
      end
    end

    describe "with invalid params" do
      it "assigns the watering as @watering" do
        watering = Watering.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Watering.any_instance.stub(:save).and_return(false)
        put :update, {:id => watering.to_param, :watering => { "time" => "invalid value" }}, valid_session
        assigns(:watering).should eq(watering)
      end

      it "re-renders the 'edit' template" do
        watering = Watering.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Watering.any_instance.stub(:save).and_return(false)
        put :update, {:id => watering.to_param, :watering => { "time" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested watering" do
      watering = Watering.create! valid_attributes
      expect {
        delete :destroy, {:id => watering.to_param}, valid_session
      }.to change(Watering, :count).by(-1)
    end

    it "redirects to the waterings list" do
      watering = Watering.create! valid_attributes
      delete :destroy, {:id => watering.to_param}, valid_session
      response.should redirect_to(waterings_url)
    end
  end

end
